CATEGORIES = ["fear", "surprise"]
EPOCHS = 50
FOLDS = 10
PRINCIPAL_COMPONENTS = 4
LOGISTIC = True
LEARNING_RATE = 0.5
DATASET_TYPE = "aligned"
STOCHASTIC_GRADIENT = False  # stochastic or batch gradient decent
EARLY_STOPPING_THRESHOLD = 400
SHOW_PRINCIPAL_COMPONENTS = False
STOCHASTIC_VS_BATCH = False
SHOW_CONFUSION_MATRIX = False

