CATEGORIES = ["fear", "surprise", "sadness", "happiness", "anger", "disgust"]
EPOCHS = 50
FOLDS = 10
PRINCIPAL_COMPONENTS = 10
LOGISTIC = False
LEARNING_RATE = 0.1
DATASET_TYPE = "aligned"
STOCHASTIC_GRADIENT = False  # stochastic or batch gradient decent
EARLY_STOPPING_THRESHOLD = 400
SHOW_PRINCIPAL_COMPONENTS = False
STOCHASTIC_VS_BATCH = True
